# Generated by Django 4.2.7 on 2025-10-04 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
        ("permissions", "0002_roleassignmentrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationAccess",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_read", models.BooleanField(default=True)),
                ("can_create", models.BooleanField(default=False)),
                ("can_update", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_admin", models.BooleanField(default=False)),
                ("accessible_fields", models.JSONField(blank=True, default=list)),
                ("restricted_fields", models.JSONField(blank=True, default=list)),
                ("inherit_to_children", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_location_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_entries",
                        to="locations.location",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_accesses",
                        to="permissions.role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Access",
                "verbose_name_plural": "Location Accesses",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="permissions_user_id_4794d6_idx",
                    ),
                    models.Index(
                        fields=["location", "is_active"],
                        name="permissions_locatio_624a06_idx",
                    ),
                    models.Index(
                        fields=["role", "is_active"],
                        name="permissions_role_id_fd5555_idx",
                    ),
                    models.Index(
                        fields=["valid_from", "valid_until"],
                        name="permissions_valid_f_776385_idx",
                    ),
                ],
                "unique_together": {
                    ("user", "location", "role", "valid_from", "valid_until")
                },
            },
        ),
        migrations.CreateModel(
            name="FieldPermission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=150)),
                ("field_name", models.CharField(max_length=150)),
                ("can_read", models.BooleanField(default=True)),
                ("can_write", models.BooleanField(default=False)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_permissions",
                        to="permissions.role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Permission",
                "verbose_name_plural": "Field Permissions",
                "indexes": [
                    models.Index(
                        fields=["role", "is_active"],
                        name="permissions_role_id_6d7aa8_idx",
                    ),
                    models.Index(
                        fields=["model_name", "field_name"],
                        name="permissions_model_n_3b36b7_idx",
                    ),
                ],
                "unique_together": {("role", "model_name", "field_name")},
            },
        ),
    ]
